version: '3.3'

services:
  api:
    image: node:14
    container_name: api
    restart: unless-stopped
    working_dir: /app
    ports:
      - 3333:3333
    volumes:
      - .:/app
    command: bash -c "yarn && yarn api"

  app:
    image: node:14
    container_name: app
    working_dir: /app
    ports:
      - 4200:4200
    volumes:
      - .:/app
    command: bash -c "yarn && yarn app"

  build:
    image: node:14
    container_name: monoerpo_starter_kit_build
    working_dir: /app
    command: bash -c "yarn && yarn build"
